version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: free_course_bot_isaev
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
