name: Web Polling Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAzCC9XxWuBcWoJfNeYNr8dWyj17nJf0U6b+J7edqSE3oEx5ex
7uHLvpX8CBS92FXDC1N35cl29yOh/dclQnA9TH74XDHfDAKUMptYgd05QOENtCYB
cnYXDE+OpI9NRw1hKUsomLZgKpshSDjKSAXr4AnV0FlJm6gxna/diaBYoPzCnBqt
bN5kIurkpOFY4UsSyJGswGLldUCPesyamNJL9r5xmauuQXGviFBiEensGx02Oq1P
aKsUsaRyX4pvZhw4muZb0hD0rO702lwrffREAr2NBkCpCXfKBrvaTp+lXqrdagFN
BEKdxuDSoEHUWX9GdLHYx6GYtpkZTMDmamzDoeMKY1BL+MwIDAQABAoIBAG82nzZA35ExgU07
7P2kEcwAJrwP8uIuW4o9wLxBAzktT5FW6pCV4KWznZ7hfhVxlFSFY1uEihZYCZf9
McWi1SLqQnIokbc/aHKyBGSsnNbmRssRsdQk1qXUaojpsla1yWvwEOwy4O4Vmup4
Vm0rHLnxYdaj7uCpoG6jNHYZMHB0ixd4593SG1vsm0jKKlEAoHDKIiLZHB1KiJZT
7VnDglZulOhsYGGTkIoewTie1B6nRqEVGM3O50Am9pfoX1ljumpkA/D/DhuVANyO
ec5uiw6+Bghu7hX2820hTX4njIAcHV5EU7e2ZC5BD829/cHI95XacYRRTyApl3uH
MDnC2UECgYEA/u+wd8xKfWPBtckpWs65DoARApJ2b3IqvELGm75uPvDZenu8N3Od
0jn/CbGkg/j4GCg2LgUns5pWNpISacpbqA65xnUzEc6t0RVxom5/G+lVu5Irwed1
lO93lPmi1TViqLKEd8DTkvGVL6AePMNRu0hY2RqpJDu9ZtRxCvxBaJECgYEAzPrH
gYF51p1grpGS8jDy2qy3TigqJ/0okUQfQ4MSj0vVxTV4q9wf0a3SnnTytOGUT0vl
dUDBu8BDrKzwuKpQMFDDY0SrTbEMhoqpBDMz/PFnyLBXyscPqXuM+yiV5SRjT51V
u0eZOYU597REwNe9l4hbTp+zAcS9JsndCFVjfIMCgYAmNAsQ2Mds5O8Za8zLs+Dd
gGmMJiCjcMtgrO0QV8gznGoqxbId6TCEWXaToFBUCpI7JIOB//nEG2PCB7/EpLN5
isNiLxv5FizMAVenDMH1j9DuK+hsxV/EcuJLq+Ev7DEdsKrTO005XwSJP4hoeKid
1SijWDByopUufLV3/PdcUQKBgDex4Cl5E7DTnCRym3nBAQuXqErNMP8ikzY9Sz1d
zNowocnuyHXx3pdrYnH5lsS9Ej4lghhE2x73k6vEZbfXVuh52U0MqHr4o02fOWNR
wkt1EF0ARSpswf2r+1d25JuZMn68YkH7p09wuppqWdAIDpSw0RZg4BOX8Eksyijs
BEKdxuDSoEHUWX9GdLHYx6GYtpkZTMDmamzDoeMKY1BL+Z4zhBrNfKd8NTkw05rdsPmSNAF8dX
jFaXsYN6eYVvP3j3TrsBIHbzU4+k8Ziaso47d2vJBuchJX+55qaCdTJpO8DC+jOF
74lJbJGHzwLT8dqqU1PG95NYNHw8dGx0Tvh8nqM9aWcn2qmkj9yp
-----END RSA PRIVATE KEY-----"
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Define ANSI color codes
            RED='\033[0;31m'
            GREEN='\033[0;32m'
            YELLOW='\033[1;33m'
            BLUE='\033[0;34m'
            NC='\033[0m' # No Color
            function log_info {
              echo -e "${YELLOW}$1${NC}"
            }
            function log_success {
              echo -e "${GREEN}$1${NC}"
            }
            function log_error {
              echo -e "${RED}$1${NC}"
            }
            # Pull latest code from GitHub
            log_info "---------------- PULLING CODE FROM GITHUB ----------------"
            mkdir -p projects/speaking-saeed
            cd projects/speaking-saeed

            if [ -d ".git" ]; then
              log_info "---------------- GIT REPO EXISTS, PULLING LATEST CODE ----------------"
              git pull origin main
              log_success "---------------- CODE PULLED FROM GITHUB -----------------"
            else
              log_info "---------------- GIT REPO DOES NOT EXIST, CLONING REPO ----------------"
              git clone git@github.com:azizbek-qodirov/speaking_saeed.git .
              git pull origin main
              log_success "---------------- REPO CLONED -----------------"
            fi

            log_info "---------------- STOPPING BOT, DOCKER COMPOSE DOWN ----------------"
            sudo docker compose down
            log_error "---------------- BOT STOPPED ----------------"
            log_info "---------------- STARTING BOT, DOCKER COMPOSE UP ----------------"
            sudo docker compose up --build -d
            log_success "---------------- BOT STARTED ----------------"